// WARNING: This file was auto-generated by: scripts/update-symbols-tests.py
#include "evdev-scancodes.h"
#include <xkbcommon/xkbcommon.h>

#include "src/utils.h"
#include "test.h"

static void
test_merge_modes_x11(struct xkb_context *ctx,
                     test_compile_buffer_t compile_buffer, void* private)
{
    struct xkb_keymap *keymap;

    /****************************************************************
     * Test group: keysyms_only_X11
     ****************************************************************/

    /* Mode: Augment */
    const char keymap_keysyms_only_X11_include[] =
        "xkb_keymap {\n"
        "  xkb_keycodes { include \"evdev\" };\n"
        "  xkb_types { include \"complete\" };\n"
        "  xkb_compat { include \"complete\" };\n"
        "  xkb_symbols {\n"
        // NOTE: Separate statements so that *all* the merge modes *really* work.
        //       Using + and | separators downgrades `replace key` to `override/
        //       augment key`.
        "    include \"pc\"\n"
        "    include \"merge_modes_x11(keysyms_only_X11_base)\"\n"
        "    include \"merge_modes_x11(keysyms_only_X11_new)\"\n"
        "    include \"merge_modes_x11(group2):2+merge_modes_x11(group3):3\"\n"
        "  };\n"
        "};";
    fprintf(stderr, "*** test_merge_modes: keysyms_only_X11, include ***\n");
    keymap = compile_buffer(ctx, keymap_keysyms_only_X11_include,
                            ARRAY_SIZE(keymap_keysyms_only_X11_include),
                            private);
    assert(keymap);
    assert_printf(test_key_seq(keymap,
        // Mismatch levels count
        KEY_Q, BOTH, XKB_KEY_Greek_alpha, NEXT,
        KEY_LEFTSHIFT, DOWN, XKB_KEY_Shift_L, NEXT,
        KEY_Q, BOTH, XKB_KEY_A, NEXT,
        KEY_LEFTSHIFT, UP, XKB_KEY_Shift_L, NEXT,
        KEY_W, BOTH, XKB_KEY_Greek_alpha, NEXT,
        KEY_LEFTSHIFT, DOWN, XKB_KEY_Shift_L, NEXT,
        KEY_W, BOTH, XKB_KEY_A, NEXT,
        KEY_LEFTSHIFT, UP, XKB_KEY_Shift_L, NEXT,
        // Single keysyms -> single keysyms
        KEY_Y, BOTH, XKB_KEY_Greek_alpha, NEXT,
        KEY_P, BOTH, XKB_KEY_Greek_alpha, NEXT,
        KEY_LEFTSHIFT, DOWN, XKB_KEY_Shift_L, NEXT,
        KEY_P, BOTH, XKB_KEY_A, NEXT,
        KEY_LEFTSHIFT, UP, XKB_KEY_Shift_L, FINISH
    ), "test_merge_modes: keysyms_only_X11, include\n");
    xkb_keymap_unref(keymap);

    /* Mode: Augment */
    const char keymap_keysyms_only_X11_augment[] =
        "xkb_keymap {\n"
        "  xkb_keycodes { include \"evdev\" };\n"
        "  xkb_types { include \"complete\" };\n"
        "  xkb_compat { include \"complete\" };\n"
        "  xkb_symbols {\n"
        // NOTE: Separate statements so that *all* the merge modes *really* work.
        //       Using + and | separators downgrades `replace key` to `override/
        //       augment key`.
        "    include \"pc\"\n"
        "    include \"merge_modes_x11(keysyms_only_X11_base)\"\n"
        "    augment \"merge_modes_x11(keysyms_only_X11_new)\"\n"
        "    include \"merge_modes_x11(group2):2+merge_modes_x11(group3):3\"\n"
        "  };\n"
        "};";
    fprintf(stderr, "*** test_merge_modes: keysyms_only_X11, augment ***\n");
    keymap = compile_buffer(ctx, keymap_keysyms_only_X11_augment,
                            ARRAY_SIZE(keymap_keysyms_only_X11_augment),
                            private);
    assert(keymap);
    assert_printf(test_key_seq(keymap,
        // Mismatch levels count
        KEY_Q, BOTH, XKB_KEY_Greek_alpha, NEXT,
        KEY_LEFTSHIFT, DOWN, XKB_KEY_Shift_L, NEXT,
        KEY_Q, BOTH, XKB_KEY_A, NEXT,
        KEY_LEFTSHIFT, UP, XKB_KEY_Shift_L, NEXT,
        KEY_W, BOTH, XKB_KEY_Greek_alpha, NEXT,
        KEY_LEFTSHIFT, DOWN, XKB_KEY_Shift_L, NEXT,
        KEY_W, BOTH, XKB_KEY_A, NEXT,
        KEY_LEFTSHIFT, UP, XKB_KEY_Shift_L, NEXT,
        // Single keysyms -> single keysyms
        KEY_Y, BOTH, XKB_KEY_Greek_alpha, NEXT,
        KEY_P, BOTH, XKB_KEY_a, NEXT,
        KEY_LEFTSHIFT, DOWN, XKB_KEY_Shift_L, NEXT,
        KEY_P, BOTH, XKB_KEY_A, NEXT,
        KEY_LEFTSHIFT, UP, XKB_KEY_Shift_L, FINISH
    ), "test_merge_modes: keysyms_only_X11, augment\n");
    xkb_keymap_unref(keymap);

    /* Mode: Override */
    const char keymap_keysyms_only_X11_override[] =
        "xkb_keymap {\n"
        "  xkb_keycodes { include \"evdev\" };\n"
        "  xkb_types { include \"complete\" };\n"
        "  xkb_compat { include \"complete\" };\n"
        "  xkb_symbols {\n"
        // NOTE: Separate statements so that *all* the merge modes *really* work.
        //       Using + and | separators downgrades `replace key` to `override/
        //       augment key`.
        "    include \"pc\"\n"
        "    include \"merge_modes_x11(keysyms_only_X11_base)\"\n"
        "    override \"merge_modes_x11(keysyms_only_X11_new)\"\n"
        "    include \"merge_modes_x11(group2):2+merge_modes_x11(group3):3\"\n"
        "  };\n"
        "};";
    fprintf(stderr, "*** test_merge_modes: keysyms_only_X11, override ***\n");
    keymap = compile_buffer(ctx, keymap_keysyms_only_X11_override,
                            ARRAY_SIZE(keymap_keysyms_only_X11_override),
                            private);
    assert(keymap);
    assert_printf(test_key_seq(keymap,
        // Mismatch levels count
        KEY_Q, BOTH, XKB_KEY_Greek_alpha, NEXT,
        KEY_LEFTSHIFT, DOWN, XKB_KEY_Shift_L, NEXT,
        KEY_Q, BOTH, XKB_KEY_A, NEXT,
        KEY_LEFTSHIFT, UP, XKB_KEY_Shift_L, NEXT,
        KEY_W, BOTH, XKB_KEY_Greek_alpha, NEXT,
        KEY_LEFTSHIFT, DOWN, XKB_KEY_Shift_L, NEXT,
        KEY_W, BOTH, XKB_KEY_A, NEXT,
        KEY_LEFTSHIFT, UP, XKB_KEY_Shift_L, NEXT,
        // Single keysyms -> single keysyms
        KEY_Y, BOTH, XKB_KEY_Greek_alpha, NEXT,
        KEY_P, BOTH, XKB_KEY_Greek_alpha, NEXT,
        KEY_LEFTSHIFT, DOWN, XKB_KEY_Shift_L, NEXT,
        KEY_P, BOTH, XKB_KEY_A, NEXT,
        KEY_LEFTSHIFT, UP, XKB_KEY_Shift_L, FINISH
    ), "test_merge_modes: keysyms_only_X11, override\n");
    xkb_keymap_unref(keymap);

    /* Mode: Replace */
    const char keymap_keysyms_only_X11_replace[] =
        "xkb_keymap {\n"
        "  xkb_keycodes { include \"evdev\" };\n"
        "  xkb_types { include \"complete\" };\n"
        "  xkb_compat { include \"complete\" };\n"
        "  xkb_symbols {\n"
        // NOTE: Separate statements so that *all* the merge modes *really* work.
        //       Using + and | separators downgrades `replace key` to `override/
        //       augment key`.
        "    include \"pc\"\n"
        "    include \"merge_modes_x11(keysyms_only_X11_base)\"\n"
        "    replace \"merge_modes_x11(keysyms_only_X11_new)\"\n"
        "    include \"merge_modes_x11(group2):2+merge_modes_x11(group3):3\"\n"
        "  };\n"
        "};";
    fprintf(stderr, "*** test_merge_modes: keysyms_only_X11, replace ***\n");
    keymap = compile_buffer(ctx, keymap_keysyms_only_X11_replace,
                            ARRAY_SIZE(keymap_keysyms_only_X11_replace),
                            private);
    assert(keymap);
    assert_printf(test_key_seq(keymap,
        // Mismatch levels count
        KEY_Q, BOTH, XKB_KEY_Greek_alpha, NEXT,
        KEY_W, BOTH, XKB_KEY_Greek_alpha, NEXT,
        // Single keysyms -> single keysyms
        KEY_Y, BOTH, XKB_KEY_Greek_alpha, NEXT,
        KEY_P, BOTH, XKB_KEY_Greek_alpha, FINISH
    ), "test_merge_modes: keysyms_only_X11, replace\n");
    xkb_keymap_unref(keymap);
}
