#!/bin/sh
# Run this to regenerate xkbcommon-keysyms.h from the X11 headers
# defining the keysyms, update the name <-> keysym mapping and various
# derived headers.
export LC_CTYPE=C.UTF-8
export LC_COLLATE=C.UTF-8
KEYSYMS_HEADER="include/xkbcommon/xkbcommon-keysyms.h"
scripts/update-keysyms-definitions.py > "$KEYSYMS_HEADER"
scripts/update-keysyms-names-handling.py "$KEYSYMS_HEADER" \
                                         src/xkbcomp/keywords.gperf > \
                                         src/ks_tables.h
scripts/update-keysyms-derived-headers.py
