#!/bin/sh
# Run this if you add/remove a new keyword to the xkbcomp scanner,
# or just want to regenerate the gperf file.
echo "// NOLINTBEGIN" > src/xkbcomp/keywords.c
gperf src/xkbcomp/keywords.gperf >> src/xkbcomp/keywords.c
echo "// NOLINTEND" >> src/xkbcomp/keywords.c
