.TH "XKBCLI\-COMPILE\-KEYMAP" "1" "" "" "libxkbcommon manual"
.
.SH "NAME"
\fBxkbcli\-compile\-keymap\fR \- compile an XKB keymap
.
.SH "SYNOPSIS"
\fBxkbcli\fR compile\-keymap [\-\-help] [OPTIONS]
.
.SH "DESCRIPTION"
\fBxkbcli compile\-keymap\fR compiles and prints a keymap based on the given options.
.
.SH "OPTIONS"
.
.TP
\fB\-\-help\fR
Print help and exit
.
.TP
.B \-\-verbose
Enable verbose debugging output
.
.TP
.B \-\-rmlvo
Print the full RMLVO with the defaults filled in for missing elements
.
.TP
.B \-\-from\-xkb
Load the XKB file from stdin, ignore RMLVO options.
This option must not be used with \fB\-\-kccgst\fR.
.
.TP
.B \-\-include=PATH
Add the given path to the include path list.
This option is order\-dependent, include paths given first are searched first.
If an include path is given, the default include path list is not used.
Use \fB\-\-include\-defaults\fR to add the default include paths.
.
.TP
.B \-\-include\-defaults
Add the default set of include directories.
This option is order-dependent, include paths given first are searched first.
.
.TP
.B \-\-rules=<rules>
The XKB ruleset
.
.TP
.B \-\-model=<model>
The XKB model
.
.TP
.B \-\-layout=<layout>
The XKB layout
.
.TP
.B \-\-variant=<variant>
The XKB layout variant
.
.TP
.B \-\-options=<options>
The XKB options
.
.SH "SEE ALSO"
\fBxkbcli\fR(1)
.
.P
The
.UR https://xkbcommon.org
libxkbcommon online documentation
.UE
