.TH "XKBCLI\-HOW\-TO\-TYPE" "1" "" "" "libxkbcommon manual"
.
.SH "NAME"
\fBxkbcli\-how\-to\-type\fR \- query how to type a given Unicode codepoint
.
.SH "SYNOPSIS"
\fBxkbcli\fR how\-to\-type [OPTIONS] <codepoint>
.
.SH "DESCRIPTION"
\fBxkbcli how\-to\-type\fR prints key sequences to type the given Unicode codepoint.
.
.P
Pipe into \fBcolumn \-ts $\'\e\et\'\fR for nicely aligned output.
.
.SH "OPTIONS"
.
.TP
.B \-\-rules=<rules>
The XKB ruleset
.
.TP
.B \-\-model=<model>
The XKB model
.
.TP
.B \-\-layout=<layout>
The XKB layout
.
.TP
.B \-\-variant=<variant>
The XKB layout variant
.
.TP
.B \-\-options=<options>
The XKB options
.
.SH "SEE ALSO"
\fBxkbcli\fR(1)
.
.P
The
.UR https://xkbcommon.org
libxkbcommon online documentation
.UE
