.TH "XKBCLI\-INTERACTIVE\-WAYLAND" "1" "" "" "libxkbcommon manual"
.
.SH "NAME"
\fBxkbcli\-interactive\-wayland\fR \- interactive debugger for XKB maps
.
.SH "SYNOPSIS"
\fBxkbcli\fR interactive\-wayland [\-\-help] [OPTIONS]
.
.SH "DESCRIPTION"
\fBxkbcli interactive\-wayland\fR is a commandline tool to interactively debug XKB maps by listening to wayland events\. This requires a Wayland compositor to be running\.
.
.P
This is a debugging tool, its behavior or output is not guaranteed to be stable\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-help\fR
Print help and exit
.
.SH "SEE ALSO"
\fBxkbcli\fR(1), \fBxkbcli\-interactive\-evdev\fR(1), \fBxkbcli\-interactive\-x11\fR(1)
.
.P
The libxkbcommon online documentation at \fIhttps://xkbcommon\.org\fR
