.TH "XKBCLI" "1" "" "" "libxkbcommon manual"
.
.SH "NAME"
\fBxkbcli\fR \- tool to interact with XKB keymaps
.
.SH "SYNOPSIS"
\fBxkbcli\fR [\-\-help|\-\-version] <command> [\fIargs\fR]
.
.SH "DESCRIPTION"
\fBxkbcli\fR is a commandline tool to query, compile and test XKB keymaps, layouts and other elements.
.
.SH "OPTIONS"
.
.TP
.B \-\-help
Print help and exit
.
.TP
.B \-\-version
Print the version and exit
.
.SH "COMMANDS"
.
.TP
.B how\-to\-type
Show how to type a given Unicode codepoint, see \fBxkbcli\-how\-to\-type\fR(1)
.
.TP
.B interactive\-x11
Interactive debugger for XKB keymaps for X11, see \fBxbkcli\-interactive\-x11\fR(1)
.
.TP
.B interactive\-wayland
Interactive debugger for XKB keymaps for Wayland, see \fBxkbcli\-interactive\-wayland\fR(1)
.
.TP
.B interactive\-evdev
Interactive debugger for XKB keymaps for evdev (Linux), see \fBxkbcli\-interactive\-evdev\fR
.
.TP
.B list
List available layouts and more, see \fBxkbcli\-list\fR(1)
.
.P
Note that not all tools may be available on your system.
.
.SH "EXIT STATUS"
.
.TP
0
exited successfully
.
.TP
1
an error occured
.
.TP
2
program was called with invalid arguments
.
.SH "SEE ALSO"
The
.UR https://xkbcommon.org
libxkbcommon online documentation
.UE
