.TH "XKBCLI\-INTERACTIVE\-X11" "1" "" "" "libxkbcommon manual"
.
.SH "NAME"
\fBxkbcli\-interactive\-x11\fR \- interactive debugger for XKB maps
.
.SH "SYNOPSIS"
\fBxkbcli\fR interactive\-x11 [\-\-help] [OPTIONS]
.
.SH "DESCRIPTION"
\fBxkbcli interactive\-x11\fR is a commandline tool to interactively debug XKB maps by listening to X11 events\. This requires an X server to be running\.
.
.P
This is a debugging tool, its behavior or output is not guaranteed to be stable\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-help\fR
Print help and exit
.
.SH "SEE ALSO"
\fBxkbcli\fR(1), \fBxkbcli\-interactive\-evdev\fR(1), \fBxkbcli\-interactive\-wayland\fR(1)
.
.P
The libxkbcommon online documentation at \fIhttps://xkbcommon\.org\fR
