.Dd June 4, 2024
.Dt XKBCLI\-COMPILE\-COMPOSE 1
.Os
.
.Sh NAME
.Nm "xkbcli\-compile\-compose"
.Nd compile an X Keyboard Compose file
.
.Sh SYNOPSIS
.Nm
.Op Ar options
.Op Ar COMPOSE_FILE
.
.Sh DESCRIPTION
.Nm
compile and print a Compose file based on the given options
.
.Bl -tag -width
.It Ar COMPOSE_FILE
Path to the compose file to load, or
.Dq \-
to read the standard input
.
.It Fl \-help
Print help and exit
.
.It Fl \-verbose
Enable verbose debugging output
.
.It Fl \-file Ar FILE
Specify a Compose file to load, or
.Dq \-
to read the standard input.
.Pp
DEPRECATED: add the file path without the flag.
.
.It Fl \-locale Ar LOCALE
Specify the locale directly, instead of relying on the environment variables
LC_ALL, LC_TYPE and LANG.
.
.It Fl \-test
Test compilation but do not print the Compose file
.El
.
.Sh SEE ALSO
.Xr xkbcli 1 ,
.Xr Compose 5 ,
.Lk https://xkbcommon.org "The libxkbcommon online documentation"
