.Dd February 4, 2026
.Dt XKBCLI\-INFO 1
.Os
.
.Sh NAME
.Nm "xkbcli\-info"
.Nd print information about libxkbcommon configuration
.
.Sh SYNOPSIS
.Nm
.Ar command Bo arguments Bc
.
.Sh DESCRIPTION
Print information about libxkbcommon configuration.
The output is in YAML 1.2 format.
.
.Sh SEE ALSO
.Xr xkbcli 1 ,
.Lk https://xkbcommon.org "The libxkbcommon online documentation"
