.TH "XKBCLI" "1" "" "" "libxkbcommon manual"
.
.SH "NAME"
\fBxkbcli\fR \- tool to interact with XKB keymaps
.
.SH "SYNOPSIS"
\fBxkbcli\fR [\-\-help|\-\-version] <command> [\fIargs\fR]
.
.SH "DESCRIPTION"
\fBxkbcli\fR is a commandline tool to query, compile and test XKB keymaps, layouts and other elements\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-help\fR
Print help and exit
.
.TP
\fB\-\-version\fR
Print the version and exit
.
.SH "COMMANDS"
.
.TP
\fBhow\-to\-type\fR
Show how to type a given unicode codepoint, see \fBxkbcli\-how\-to\-type\fR(1)
.
.TP
\fBinteractive\-x11\fR
Interactive debugger for XKB maps for X11, see \fBxbkcli\-interactive\-x11\fR(1)
.
.TP
\fBinteractive\-wayland\fR
Interactive debugger for XKB maps for Wayland, see \fBxkbcli\-interactive\-wayland\fR(1)
.
.TP
\fBinteractive\-evdev\fR
Interactive debugger for XKB maps for evdev, see \fBxkbcli\-interactive\-evdev\fR
.
.TP
\fBlist\fR
List available layouts and more, see \fBxkbcli\-list\fR(1)
.
.P
Note that not all tools may be available on your system\.
.
.SH "EXIT STATUS"
.
.TP
0
exited successfully
.
.TP
1
an error occured
.
.TP
2
program was called with invalid arguments
.
.SH "SEE ALSO"
The libxkbcommon online documentation at \fIhttps://xkbcommon\.org\fR
