.TH "XKBCLI\-INTERACTIVE\-EVDEV" "1" "" "" "libxkbcommon manual"
.
.SH "NAME"
\fBxkbcli\-interactive\-evdev\fR \- interactive debugger for XKB keymaps
.
.SH "SYNOPSIS"
\fBxkbcli\fR interactive\-evdev [\-\-help] [OPTIONS]
.
.SH "DESCRIPTION"
\fBxkbcli interactive\-evdev\fR is a commandline tool to interactively debug XKB keymaps by listening to \fB/dev/input/eventX\fR evdev devices (Linux).
.
.P
.B xkbcli interactive\-evdev
requires permission to open the evdev device nodes.
This usually requires being the \fBroot\fR user or belonging to the \fBinput\fR group.
.
.P
Press the Escape key to exit.
.
.P
This is a debugging tool, its behavior or output is not guaranteed to be stable.
.
.SH "OPTIONS"
.
.TP
.B \-\-help
Print help and exit
.
.TP
.B \-\-rules=<rules>
The XKB ruleset
.
.TP
.B \-\-model=<model>
The XKB model
.
.TP
.B \-\-layout=<layout>
The XKB layout
.
.TP
.B \-\-variant=<variant>
The XKB layout variant
.
.TP
.B \-\-options=<options>
The XKB options
.
.TP
.B \-\-keymap=PATH
Specify a keymap path.
This option is mutually exclusive with the RMLVO options.
.
.TP
.B \-\-report\-state\-changes
Report changes to the keyboard state
.
.TP
.B \-\-enable\-compose
Enable Compose functionality
.
.TP
.B \-\-consumed\-mode={xkb|gtk}
Set the consumed modifiers mode (default: xkb)
.
.SH "SEE ALSO"
\fBxkbcli\fR(1), \fBxkbcli\-interactive\-wayland\fR(1), \fBxkbcli\-interactive\-x11\fR(1)
.
.P
The
.UR https://xkbcommon.org
libxkbcommon online documentation
.UE
