.TH "XKBCLI\-LIST" "1" "" "" "libxkbcommon manual"
.
.SH "NAME"
\fBxkbcli\-list\fR \- list available XKB models, layouts, variants and options
.
.SH "SYNOPSIS"
\fBxkbcli\fR list [\-\-help] [/path/to/xkbbase [/path/to/xkbbase] ...]
.
.SH "DESCRIPTION"
\fBxkbcli list\fR is a commandline tool to list available model, layout, variant and option (MLVO) values from the XKB registry.
.
.P
Arguments provided on the commandline are treated as XKB base directory installations.
.
.SH "OPTIONS"
.
.TP
.B \-\-help
Print help and exit
.
.TP
.B \-v, \-\-verbose
Increase verbosity, use multiple times for debugging output
.
.TP
.B \-\-ruleset=<name>
Load the ruleset with the given name
.
.TP
.B \-\-skip\-default\-paths
Do not load the default XKB include paths
.
.TP
.B \-\-load\-exotic
Load exotic (extra) layouts
.
.SH "SEE ALSO"
\fBxkbcli\fR(1)
.
.P
The
.UR https://xkbcommon.org
libxkbcommon online documentation
.UE
