.Dd June 4, 2024
.Dt XKBCLI\-INTERACTIVE\-WAYLAND 1
.Os
.
.Sh NAME
.Nm "xkbcli\-interactive\-wayland"
.Nd interactive debugger for Wayland keyboard keymaps
.
.Sh SYNOPSIS
.Nm
.Op Ar options
.
.Sh DESCRIPTION
.Nm
is a commandline tool to interactively debug XKB keymaps by listening to Wayland events.
.
.Pp
This requires a Wayland compositor to be running.
.
.Pp
Press the
.Aq Escape
key to exit.
.
.Pp
This is a debugging tool, its behavior or output is not guaranteed to be stable.
.
.Bl -tag -width Ds
.It Fl \-help
Print help and exit
.
.It Fl \-format Ar KEYMAP_FORMAT
Specify the keymap format (numeric or label, e.g.\&
.Dq v1 )
.
.It Fl \-local\-state
Enable local state handling and ignore modifiers/layouts state updates
from the compositor
.
.It Fl \-legacy\-state\-api Op Ar =true|false
Use the legacy state API instead of the state event API.
It implies
.Fl \-local\-state
if disabled.
.
.It Fl \-controls Ar CONTROLS
Enable or disable controls. It implies
.Fl \-local\-state
and
.Fl \-legacy\-state\-api=false
\&.
.Ar CONTROLS
is a comma-separated-list of the following entries:
.Bl -tag -compact -hang
.It Ar sticky-keys
Enable sticky-keys accessibility feature
.It Ar latch-to-lock
Enable latch-to-lock option for sticky-keys
.It Ar latch-simultaneous
Relax the strict tapping sequence requirement operating key latches.
.El
Each entry may be preceded by
.Ar \+
or
.Ar \-
in order to respectively enable or disable the corresponding control.
.
.It Fl \-shortcuts-mask Ar MASK
Use the given modifier mask to enable selecting a specific
layout (see
.Fl \-shortcuts-mapping
) when some of these modifiers are active.
The modifier mask is a plus-separated list of modifiers names, e.g.
.Ar "Control+Alt+Super"
\&.
It implies
.Fl \-local-state
and
.Fl \-legacy\-state\-api=false
\&.
.
.It Fl \-shortcuts-mapping Ar MAPPING
Use the given layout indices mapping to enable selecting a specific
layout when some modifiers are active (see
.Fl --shortcuts-mask
).
.Ar MAPPINGS
is a comma-separated list of 1-indexed layout
indices mappings with format
.Ar source:target
, e.g.
.Ar 2:1,3:1
\&. It implies
.Fl \-local-state
and
.Fl \-legacy\-state\-api=false
\&.
.
.It Fl \-keymap Oo Ar PATH Oc
Load the XKB keymap from a file instead of the keymap from the compositor.
It implies
.Fl \-local\-state
\&. If
.Ar PATH
is empty or
.Dq \- ,
read the stdin.
.
.It Fl \-enable\-compose
Enable Compose functionality
.
.It Fl \-verbose
Enable verbose debugging output
.
.It Fl 1, \-uniline
Enable uniline event output
.
.It Fl \-multiline
Enable multiline event output
.
.It Fl \-no-state-report
Do not report state changes
.El
.
.Sh SEE ALSO
.Xr xkbcli 1 ,
.Xr xkbcli\-interactive\-evdev 1 ,
.Xr xkbcli\-interactive\-x11 1 ,
.Lk https://xkbcommon.org "The libxkbcommon online documentation"
