name: github-release

on:
  push:
    tags:
      - 'xkbcommon-*'

# Set permissions at the job level.
permissions: {}

jobs:
  build:
    name: Automatically create GitHub release for tag
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            See the [NEWS](https://github.com/xkbcommon/libxkbcommon/blob/master/NEWS) file for the changes.

            Official tarball: https://xkbcommon.org/download/lib${{ github.ref }}.tar.xz
